/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type TotalUsers = number
export type LastUpdatedAt = string
export type Id = number
export type Name = string
export type Email = string
export type CreatedAt = string
export type UpdatedAt = string
export type Users1 = User[]

/**
 * JSON Schema for aurora.models, automatically generated by schorle
 */
export interface AuroraModels {
[k: string]: unknown
}
/**
 * This interface was referenced by `AuroraModels`'s JSON-Schema
 * via the `definition` "StatsProps".
 */
export interface StatsProps {
totalUsers: TotalUsers
lastUpdatedAt: LastUpdatedAt
[k: string]: unknown
}
/**
 * This interface was referenced by `AuroraModels`'s JSON-Schema
 * via the `definition` "User".
 */
export interface User {
id: Id
name: Name
email: Email
createdAt: CreatedAt
updatedAt: UpdatedAt
[k: string]: unknown
}
/**
 * This interface was referenced by `AuroraModels`'s JSON-Schema
 * via the `definition` "Users".
 */
export interface Users {
users: Users1
[k: string]: unknown
}
