/* AUTO-GENERATED by build_page_registry.py — do not edit by hand */
/// <reference types="react" />

import type { ReactNode } from "react";
import type { JSX } from "react";

export type LayoutFC = (props: { children: ReactNode }) => JSX.Element;

export type PageRegistryEntry = {
  layouts: LayoutFC[];
  Page: React.ComponentType<any>;
};

export type PageRegistry = Record<string, PageRegistryEntry>;

export function wrapLayouts(
  Page: React.ComponentType,
  layouts: LayoutFC[],
): React.ReactElement {
  const tree = layouts.reduceRight<React.ReactNode>(
    (child, Layout) => <Layout>{child}</Layout>,
    <Page />,
  );
  return <>{tree}</>;
}

export const pageRegistry: PageRegistry = {
  Index: {
    layouts: [(await import("@/pages/./__layout")).default],
    Page: (await import("@/pages/Index")).default,
  },
};

export default pageRegistry;
