# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protobuf/message.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ReloadEvent(betterproto.Message):
    pass
